### ISSUE TITLE
feat: reverse convertation from regexp to rex

### ISSUE THREAD

**Issue by hedhyw** [hedhyw/rex#13]
https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/regexp/syntax/regexp.go;l=246

Edit: deploy as an online tool.

- [x] basic implementation (#57)
- [x] use regexp parser (#58)
- [ ] `(123)+` and `(?123)+`
- [ ] online tool or telegram bot?
- [ ] support the rest of the syntax
- [ ] document the generator
- [ ] support verbose/simple modes (verbose converts all nodes, simple only groups)
- [ ] handle repeated blocks

**Comment by ryzheboka** [comment]
Hi @hedhyw, 

what do you mean by convertation from regexp? The conversion from the struct  [Regexp](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/regexp/syntax/regexp.go;drc=5b606a9d2b7649532fe25794fa6b99bd24e7697c;bpv=1;bpt=1;l=17?gsn=Regexp&gs=kythe%3A%2F%2Fgo.googlesource.com%2Fgo%3Flang%3Dgo%3Fpath%3Dregexp%2Fsyntax%23type%2520Regexp) to the struct RegExp? What would the signature of the method be? Where should the method be?

**Comment by hedhyw** [comment]
Hi!
1. It should be a binary that accepts a plain regular expression.

    For example, `./bin/rex "^[0-9]+$"` and generates go code:
    ```go
    re := rex.New(
        rex.Chars.Begin(), // ^
        rex.Chars.Digits().Repeat().OneOrMore(), // [0-9]+
        rex.Chars.End(), //`$
    ).MustCompile()
    ```

2. All unknown tokens might be placed inside `rex.Common.Raw("...")`.

3. I think it would be difficult to implement at first, so I think it is better to support only `Raw` and `Group` in the first iteration:

    In: `((\d+)([a-z]+))`
    Out:
    ```go
    rex.New(
        rex.Group.Define(
            rex.Group.Define(
                rex.Common.Raw(`\d+`),
            ),
            rex.Group.Define(
                rex.Common.Raw(`[a-z]+`),
            ),
        ),
    )
    ```
4. [Regexp](https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/regexp/syntax/regexp.go;l=246) is a node, so following the method `String`, it should not be too ¿difficult?

**Comment by ryzheboka** [comment]
Thanks for the explanation! The issue sounds very interesting :) Where in the project do I put the script? Can I write the script in bash? Should the binary print out the generated go code to standard output?

**Comment by hedhyw** [comment]
I think it is better to write this in Golang. We can place everything in cmd/generator/main.go. Yes, let's simply print to stdout.

**Comment by ryzheboka** [comment]
Ok, then I will try to implement it :)

**Comment by hedhyw** [comment]
> Ok, then can I try to implement it? :)

Sure, thank you

**Comment by ryzheboka** [comment]
A question about the tests: Can I put them into a generator_test.go file in the generator folder? Or do I write the tests somewhere else?

**Comment by hedhyw** [comment]
Yes, you can put them into the folder where the implementation is located.

**Comment by ryzheboka** [comment]
Do I need to format the output using tabs and linebreaks? Or can the output look like this:
``` 
rex.New(rex.Group.Define(rex.Group.Define(rex.Common.Raw(`\d+`),),rex.Group.Define(rex.Common.Raw(`[a-z]+`),),),)
```

**Comment by Kryvchun** [comment]
> Do I need to format the output using tabs and linebreaks? Or can the output look like this:
> 
> ```
> rex.New(rex.Group.Define(rex.Group.Define(rex.Common.Raw(`\d+`),),rex.Group.Define(rex.Common.Raw(`[a-z]+`),),),)
> ```

It is better to format

**Comment by hedhyw** [comment]
> Do I need to format the output using tabs and linebreaks? Or can the output look like this:
> 
> ```
> rex.New(rex.Group.Define(rex.Group.Define(rex.Common.Raw(`\d+`),),rex.Group.Define(rex.Common.Raw(`[a-z]+`),),),)
> ```

It is better to format:

```go
rex.New(
    rex.Group.Define(
        rex.Group.Define(
            rex.Common.Raw(`\d+`),
        ),
        rex.Group.Define(
            rex.Common.Raw(`[a-z]+`),
        ),
    ),
)
```

**Comment by ryzheboka** [comment]
Hi @hedhyw, thanks for implementing the usage of the regexp parser! It looks way more readable than my implementation without the parser. I would like to try to continue working on this issue by implementing the third step. Would it be ok? What did you mean by "(123)+ and (?123)+" ?

**Comment by hedhyw** [comment]
@ryzheboka Hi!

> thanks for implementing the usage of the regexp parser!

Thanks!

> Would it be ok?

Of course! Sure.

> What did you mean by "(123)+ and (?123)+" ?

It means supporting the repetition of groups. The test for this would be a good start.

**Comment by ryzheboka** [comment]
Hi @hedhyw,

thanks, then I will start working on repetitions of groups :)
