### ISSUE TITLE
Support edge markers

### ISSUE THREAD

**Issue by hedhyw** [hedhyw/rex#4]
| symbol | description                                                                                               | Suggestion                                    |
|-----------|-----------------------------------------------------------------------------------------------|----------------------------------------------|
| \A         | at beginning of text                                                                                   | `Chars.BeginOfText()`                   |
| \b          | at ASCII word boundary (\w on one side and \W, \A, or \z on the other) | `Chars.ASCIIWordBoundary()`      |
| \B         | not at ASCII word boundary                                                                     | `Chars.NotASCIIWordBoundary()` |
| \z          | at end of text                                                                                            | `Chars.EndOfText()`                       |

**Comment by ryzheboka** [comment]
Hi @hedhyw and @thaithimyduyen, 
can I work on this issue? I am new to Golang, so it should take me up to one month.

**Comment by hedhyw** [comment]
> Hi @hedhyw and @thaithimyduyen, can I work on this issue? I am new to Golang, so it should take me up to one month.

Sure, if you have any questions, feel free to ask! Thanks!
