### ISSUE TITLE
docs: add edge markers to documentation

### ISSUE THREAD

**Issue by hedhyw** [hedhyw/rex#47]
https://github.com/hedhyw/rex/blob/main/_docs/library.md#character-classes

Relates to #46

**Comment by hedhyw** [comment]
It might be interesting for you: @ryzheboka

**Comment by ryzheboka** [comment]
I can add the documentation for edge markers :)

**Comment by Kryvchun** [comment]
> I can add the documentation for edge markers :)

Thanks

**Comment by hedhyw** [comment]
> I can add the documentation for edge markers :)

Thanks
