### ISSUE TITLE
examples_test.go doesn't show up at pkg.go.dev

### ISSUE THREAD

**Issue by gaissmai** [hedhyw/rex#48]
Hi, maybe you should put examples_test.go one directory deeper:
```
├── go.mod
└── pkg
     ├── dialect
     ├── examples_test.go
     └── rex
```
to 

```
├── go.mod
└── pkg
    ├── dialect
    └── rex
        └── examples_test.go
```

Thanks for rex!

**Comment by hedhyw** [comment]
Now, the examples are in the correct place: https://pkg.go.dev/github.com/hedhyw/rex@v0.4.1/pkg/rex
Closing the issue, thank you
